services:
  db:
    image: postgres:16-alpine
    container_name: larangola-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: larangola-db
    ports:
      - '5432:5432'
    volumes:
      - larangola-data:/var/lib/postgresql/data
    networks:
      - larangolanet
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: renekemalandua/larangola-nest-api:latest
    container_name: larangola-api
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - larangolanet

volumes:
  larangola-data:

networks:
  larangolanet:
    driver: bridge
